//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace snesclassicalert.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>thinkgeek,http://www.thinkgeek.com/product/kmrn/?srp=5,IN STOCK</string>
  <string>BH,https://www.bhphotovideo.com/c/product/1347308-REG/nintendo_snes_super_nintendo_classic_edition.html,TYPE=""SUBMIT""&gt;ADD TO CART&lt;/BUTTON&gt;</string>
  <string>Amazon,https://www.amazon.com/Super-NES-Classic-nintendo/dp/B0721GGGS9/ref=sr_1_3?s=videogames&amp;ie=UTF8&amp;qid=1506823304&amp;sr=1-3&amp;keywords=super+nes+classic,&amp;quot;79.99&amp;quot</string>
  <string>GameStop,https://www.gamestop.com/snes/consoles/super-nes-classic-edition/152771,&lt;a onclick=""AddToCartClicked(this);</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Merchants {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Merchants"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Write_GET_Responses_To_Files {
            get {
                return ((bool)(this["Write_GET_Responses_To_Files"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Temp")]
        public string HTML_Output_Directory {
            get {
                return ((string)(this["HTML_Output_Directory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Sleep_Timer_In_Minutes {
            get {
                return ((int)(this["Sleep_Timer_In_Minutes"]));
            }
        }
    }
}
